---
  sudo: false
  language: go
  os:
    - osx
  notifications:
    email: false
  go:
    - 1.5
  install: make deps
  before_script: test -z "$(make validate | tee /dev/stderr)"
  script: make test
