---
  # See appveyor.yml for windows build.
  sudo: false
  language: go
  os:
    - osx
  notifications:
    email: false
  go:
    - 1.6
  install: make deps
  before_script: make validate
  script: make test
