version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\docker\docker-credential-helpers

# Build host

environment:
    global:
      GOPATH: c:\gopath
      CGO_ENABLED: 1
      GOVERSION: 1.6
    matrix:
      - platform: x86
        GOARCH: 386
        MSYS2_BITS: 32
      - platform: x64
        GOARCH: amd64
        MSYS2_BITS: 64

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install Go 1.6.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q
  - set Path=c:\msys64\mingw%MSYS2_BITS%\bin;c:\go\bin;%Path%
  - go version
  - go env

build_script:
  - go vet ./wincred
  - go test -v github.com/docker/docker-credential-helpers/wincred

# Disable automatic tests
test: off

# Disable deployment
deploy: off
